In [58]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [59]:
# Read data
df = pd.read_csv('prc.csv')
df

             date       state   county  PM25  ozone  PM10  confirmed  deaths
0        1/1/2021  California    Butte  23.1  0.028    24       7405      96
1        1/1/2021  California    Butte  23.1  0.023    24       7405      96
2        1/1/2021  California    Butte   6.1  0.028    24       7405      96
3        1/1/2021  California    Butte   6.1  0.023    24       7405      96
4        1/1/2021  California    Butte  15.6  0.028    24       7405      96
...           ...         ...      ...   ...    ...   ...        ...     ...
330200  3/11/2021    Illinois  Madison   4.2  0.030    18      28418     541
330201  8/27/2021    Illinois  Madison  16.0  0.062    29      35558     625
330202  8/27/2021    Illinois  Madison  16.0  0.054    29      35558     625
330203  8/27/2021    Illinois  Madison  16.0  0.059    29      35558     625
330204  8/27/2021    Illinois  Madison  16.0  0.046    29      35558     625

[330205 rows x 8 columns]

In [60]:
# Transfor data type 
df['date'] = pd.to_datetime(df['date'])

# Pearson correlation

## January

In [52]:
m1 = df[df['date'].dt.month == 1]
m1

             date       state   county  PM25  ozone  PM10  confirmed  deaths
0      2021-01-01  California    Butte  23.1  0.028    24       7405      96
1      2021-01-01  California    Butte  23.1  0.023    24       7405      96
2      2021-01-01  California    Butte   6.1  0.028    24       7405      96
3      2021-01-01  California    Butte   6.1  0.023    24       7405      96
4      2021-01-01  California    Butte  15.6  0.028    24       7405      96
...           ...         ...      ...   ...    ...   ...        ...     ...
329479 2021-01-28    Illinois  Madison  11.7  0.035    13      25824     497
329480 2021-01-28    Illinois  Madison  13.1  0.035    13      25824     497
329481 2021-01-28    Illinois  Madison   8.4  0.035    13      25824     497
329482 2021-01-28    Illinois  Madison  10.9  0.035    13      25824     497
329483 2021-01-28    Illinois  Madison  11.5  0.035    13      25824     497

[27461 rows x 8 columns]

In [113]:
m1.groupby('state')[['confirmed','PM25']].corr(method="pearson")

                          confirmed      PM25
state
California     confirmed   1.000000 -0.062141
               PM25       -0.062141  1.000000
Florida        confirmed   1.000000 -0.191960
               PM25       -0.191960  1.000000
Georgia        confirmed   1.000000  0.003062
               PM25        0.003062  1.000000
Illinois       confirmed   1.000000 -0.100784
               PM25       -0.100784  1.000000
Michigan       confirmed   1.000000 -0.375677
               PM25       -0.375677  1.000000
New York       confirmed   1.000000 -0.547449
               PM25       -0.547449  1.000000
North Carolina confirmed   1.000000  0.011346
               PM25        0.011346  1.000000
Ohio           confirmed   1.000000  0.022080
               PM25        0.022080  1.000000
Pennsylvania   confirmed   1.000000 -0.035888
               PM25       -0.035888  1.000000
Texas          confirmed   1.000000  0.078418
               PM25        0.078418  1.000000

In [112]:
m1.groupby('state')[['confirmed','PM25']].corr(method="spearman")

                          confirmed      PM25
state
California     confirmed   1.000000  0.037733
               PM25        0.037733  1.000000
Florida        confirmed   1.000000 -0.219833
               PM25       -0.219833  1.000000
Georgia        confirmed   1.000000  0.030086
               PM25        0.030086  1.000000
Illinois       confirmed   1.000000 -0.259483
               PM25       -0.259483  1.000000
Michigan       confirmed   1.000000 -0.403691
               PM25       -0.403691  1.000000
New York       confirmed   1.000000 -0.564168
               PM25       -0.564168  1.000000
North Carolina confirmed   1.000000  0.050358
               PM25        0.050358  1.000000
Ohio           confirmed   1.000000 -0.052327
               PM25       -0.052327  1.000000
Pennsylvania   confirmed   1.000000 -0.113906
               PM25       -0.113906  1.000000
Texas          confirmed   1.000000 -0.030334
               PM25       -0.030334  1.000000

In [54]:
m1.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.216498
               ozone       0.216498  1.000000
Florida        confirmed   1.000000  0.240094
               ozone       0.240094  1.000000
Georgia        confirmed   1.000000  0.064105
               ozone       0.064105  1.000000
Illinois       confirmed   1.000000  0.222448
               ozone       0.222448  1.000000
Michigan       confirmed   1.000000  0.638372
               ozone       0.638372  1.000000
New York       confirmed   1.000000  0.710716
               ozone       0.710716  1.000000
North Carolina confirmed   1.000000  0.066919
               ozone       0.066919  1.000000
Ohio           confirmed   1.000000  0.085010
               ozone       0.085010  1.000000
Pennsylvania   confirmed   1.000000 -0.013353
               ozone      -0.013353  1.000000
Texas          confirmed   1.000000 -0.413696
               ozone      -0.413696  1.000000

In [55]:
m1.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.079505
               PM10       -0.079505  1.000000
Florida        confirmed   1.000000 -0.368630
               PM10       -0.368630  1.000000
Georgia        confirmed   1.000000 -0.027507
               PM10       -0.027507  1.000000
Illinois       confirmed   1.000000  0.285002
               PM10        0.285002  1.000000
Michigan       confirmed   1.000000  0.135751
               PM10        0.135751  1.000000
New York       confirmed   1.000000 -0.437702
               PM10       -0.437702  1.000000
North Carolina confirmed   1.000000  0.165012
               PM10        0.165012  1.000000
Ohio           confirmed   1.000000  0.163504
               PM10        0.163504  1.000000
Pennsylvania   confirmed   1.000000  0.262823
               PM10        0.262823  1.000000
Texas          confirmed   1.000000  0.172084
               PM10        0.172084  1.000000

## February

In [69]:
m2 = df[df['date'].dt.month == 2]

In [68]:
m2.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.077311
               PM25        0.077311  1.000000
Florida        confirmed   1.000000 -0.207613
               PM25       -0.207613  1.000000
Georgia        confirmed   1.000000 -0.135899
               PM25       -0.135899  1.000000
Illinois       confirmed   1.000000  0.131606
               PM25        0.131606  1.000000
Michigan       confirmed   1.000000  0.291108
               PM25        0.291108  1.000000
New York       confirmed   1.000000  0.143564
               PM25        0.143564  1.000000
North Carolina confirmed   1.000000 -0.053693
               PM25       -0.053693  1.000000
Ohio           confirmed   1.000000 -0.084384
               PM25       -0.084384  1.000000
Pennsylvania   confirmed   1.000000 -0.009565
               PM25       -0.009565  1.000000
Texas          confirmed   1.000000  0.076364
               PM25        0.076364  1.000000

In [70]:
m2.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.158278
               ozone       0.158278  1.000000
Florida        confirmed   1.000000 -0.120687
               ozone      -0.120687  1.000000
Georgia        confirmed   1.000000  0.040737
               ozone       0.040737  1.000000
Illinois       confirmed   1.000000  0.033944
               ozone       0.033944  1.000000
Michigan       confirmed   1.000000  0.436571
               ozone       0.436571  1.000000
New York       confirmed   1.000000  0.260542
               ozone       0.260542  1.000000
North Carolina confirmed   1.000000 -0.037618
               ozone      -0.037618  1.000000
Ohio           confirmed   1.000000 -0.198631
               ozone      -0.198631  1.000000
Pennsylvania   confirmed   1.000000 -0.219071
               ozone      -0.219071  1.000000
Texas          confirmed   1.000000 -0.323003
               ozone      -0.323003  1.000000

In [71]:
m2.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000  0.023738
               PM10        0.023738  1.000000
Florida        confirmed   1.000000 -0.270388
               PM10       -0.270388  1.000000
Georgia        confirmed   1.000000  0.149115
               PM10        0.149115  1.000000
Illinois       confirmed   1.000000  0.123390
               PM10        0.123390  1.000000
Michigan       confirmed   1.000000 -0.259660
               PM10       -0.259660  1.000000
New York       confirmed   1.000000  0.307516
               PM10        0.307516  1.000000
North Carolina confirmed   1.000000 -0.037448
               PM10       -0.037448  1.000000
Ohio           confirmed   1.000000  0.033186
               PM10        0.033186  1.000000
Pennsylvania   confirmed   1.000000  0.269163
               PM10        0.269163  1.000000
Texas          confirmed   1.000000 -0.205942
               PM10       -0.205942  1.000000

## March

In [72]:
m3 = df[df['date'].dt.month == 3]

In [73]:
m3.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.264740
               PM25        0.264740  1.000000
Florida        confirmed   1.000000 -0.281364
               PM25       -0.281364  1.000000
Georgia        confirmed   1.000000 -0.156641
               PM25       -0.156641  1.000000
Illinois       confirmed   1.000000 -0.009168
               PM25       -0.009168  1.000000
Michigan       confirmed   1.000000 -0.200576
               PM25       -0.200576  1.000000
New York       confirmed   1.000000 -0.378984
               PM25       -0.378984  1.000000
North Carolina confirmed   1.000000  0.010391
               PM25        0.010391  1.000000
Ohio           confirmed   1.000000  0.036714
               PM25        0.036714  1.000000
Pennsylvania   confirmed   1.000000 -0.012064
               PM25       -0.012064  1.000000
Texas          confirmed   1.000000  0.404238
               PM25        0.404238  1.000000

In [74]:
m3.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.199921
               ozone       0.199921  1.000000
Florida        confirmed   1.000000 -0.071786
               ozone      -0.071786  1.000000
Georgia        confirmed   1.000000 -0.001709
               ozone      -0.001709  1.000000
Illinois       confirmed   1.000000  0.028291
               ozone       0.028291  1.000000
Michigan       confirmed   1.000000  0.037856
               ozone       0.037856  1.000000
New York       confirmed   1.000000 -0.220947
               ozone      -0.220947  1.000000
North Carolina confirmed   1.000000 -0.103950
               ozone      -0.103950  1.000000
Ohio           confirmed   1.000000  0.011571
               ozone       0.011571  1.000000
Pennsylvania   confirmed   1.000000 -0.116150
               ozone      -0.116150  1.000000
Texas          confirmed   1.000000 -0.252161
               ozone      -0.252161  1.000000

In [75]:
m3.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.035312
               PM10       -0.035312  1.000000
Florida        confirmed   1.000000 -0.426489
               PM10       -0.426489  1.000000
Georgia        confirmed   1.000000  0.292292
               PM10        0.292292  1.000000
Illinois       confirmed   1.000000 -0.006244
               PM10       -0.006244  1.000000
Michigan       confirmed   1.000000 -0.244554
               PM10       -0.244554  1.000000
New York       confirmed   1.000000 -0.074620
               PM10       -0.074620  1.000000
North Carolina confirmed   1.000000  0.029903
               PM10        0.029903  1.000000
Ohio           confirmed   1.000000  0.117117
               PM10        0.117117  1.000000
Pennsylvania   confirmed   1.000000 -0.006652
               PM10       -0.006652  1.000000
Texas          confirmed   1.000000  0.278460
               PM10        0.278460  1.000000

## April

In [76]:
m4 = df[df['date'].dt.month == 4]

In [77]:
m4.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.613744
               PM25        0.613744  1.000000
Florida        confirmed   1.000000 -0.120682
               PM25       -0.120682  1.000000
Georgia        confirmed   1.000000 -0.299935
               PM25       -0.299935  1.000000
Illinois       confirmed   1.000000 -0.033704
               PM25       -0.033704  1.000000
Michigan       confirmed   1.000000 -0.333171
               PM25       -0.333171  1.000000
New York       confirmed   1.000000 -0.733670
               PM25       -0.733670  1.000000
North Carolina confirmed   1.000000 -0.093000
               PM25       -0.093000  1.000000
Ohio           confirmed   1.000000  0.018708
               PM25        0.018708  1.000000
Pennsylvania   confirmed   1.000000 -0.021612
               PM25       -0.021612  1.000000
Texas          confirmed   1.000000  0.265253
               PM25        0.265253  1.000000

In [78]:
m4.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.267880
               ozone       0.267880  1.000000
Florida        confirmed   1.000000 -0.129357
               ozone      -0.129357  1.000000
Georgia        confirmed   1.000000 -0.194335
               ozone      -0.194335  1.000000
Illinois       confirmed   1.000000 -0.053898
               ozone      -0.053898  1.000000
Michigan       confirmed   1.000000 -0.383622
               ozone      -0.383622  1.000000
New York       confirmed   1.000000 -0.679315
               ozone      -0.679315  1.000000
North Carolina confirmed   1.000000 -0.037907
               ozone      -0.037907  1.000000
Ohio           confirmed   1.000000 -0.065700
               ozone      -0.065700  1.000000
Pennsylvania   confirmed   1.000000 -0.004548
               ozone      -0.004548  1.000000
Texas          confirmed   1.000000 -0.554761
               ozone      -0.554761  1.000000

In [79]:
m4.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000  0.064423
               PM10        0.064423  1.000000
Florida        confirmed   1.000000 -0.356872
               PM10       -0.356872  1.000000
Georgia        confirmed   1.000000  0.324503
               PM10        0.324503  1.000000
Illinois       confirmed   1.000000 -0.012706
               PM10       -0.012706  1.000000
Michigan       confirmed   1.000000  0.077874
               PM10        0.077874  1.000000
New York       confirmed   1.000000 -0.710009
               PM10       -0.710009  1.000000
North Carolina confirmed   1.000000  0.007052
               PM10        0.007052  1.000000
Ohio           confirmed   1.000000  0.013766
               PM10        0.013766  1.000000
Pennsylvania   confirmed   1.000000  0.045520
               PM10        0.045520  1.000000
Texas          confirmed   1.000000 -0.136876
               PM10       -0.136876  1.000000

## May

In [80]:
m5 = df[df['date'].dt.month == 5]

In [81]:
m5.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.550238
               PM25        0.550238  1.000000
Florida        confirmed   1.000000 -0.095485
               PM25       -0.095485  1.000000
Georgia        confirmed   1.000000 -0.243520
               PM25       -0.243520  1.000000
Illinois       confirmed   1.000000 -0.007545
               PM25       -0.007545  1.000000
Michigan       confirmed   1.000000  0.190729
               PM25        0.190729  1.000000
New York       confirmed   1.000000 -0.039740
               PM25       -0.039740  1.000000
North Carolina confirmed   1.000000  0.136126
               PM25        0.136126  1.000000
Ohio           confirmed   1.000000 -0.107242
               PM25       -0.107242  1.000000
Pennsylvania   confirmed   1.000000  0.006609
               PM25        0.006609  1.000000
Texas          confirmed   1.000000  0.164133
               PM25        0.164133  1.000000

In [82]:
m5.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.077903
               ozone       0.077903  1.000000
Florida        confirmed   1.000000 -0.227227
               ozone      -0.227227  1.000000
Georgia        confirmed   1.000000 -0.039510
               ozone      -0.039510  1.000000
Illinois       confirmed   1.000000  0.056959
               ozone       0.056959  1.000000
Michigan       confirmed   1.000000  0.289537
               ozone       0.289537  1.000000
New York       confirmed   1.000000 -0.039867
               ozone      -0.039867  1.000000
North Carolina confirmed   1.000000  0.140708
               ozone       0.140708  1.000000
Ohio           confirmed   1.000000  0.071519
               ozone       0.071519  1.000000
Pennsylvania   confirmed   1.000000  0.053388
               ozone       0.053388  1.000000
Texas          confirmed   1.000000 -0.494579
               ozone      -0.494579  1.000000

In [83]:
m5.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.026036
               PM10       -0.026036  1.000000
Florida        confirmed   1.000000 -0.456301
               PM10       -0.456301  1.000000
Georgia        confirmed   1.000000  0.293605
               PM10        0.293605  1.000000
Illinois       confirmed   1.000000  0.067423
               PM10        0.067423  1.000000
Michigan       confirmed   1.000000  0.192326
               PM10        0.192326  1.000000
New York       confirmed   1.000000  0.176788
               PM10        0.176788  1.000000
North Carolina confirmed   1.000000  0.181461
               PM10        0.181461  1.000000
Ohio           confirmed   1.000000  0.028716
               PM10        0.028716  1.000000
Pennsylvania   confirmed   1.000000  0.080063
               PM10        0.080063  1.000000
Texas          confirmed   1.000000 -0.325669
               PM10       -0.325669  1.000000

## June

In [84]:
m6 = df[df['date'].dt.month == 6]

In [85]:
m6.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.409774
               PM25        0.409774  1.000000
Florida        confirmed   1.000000  0.072800
               PM25        0.072800  1.000000
Georgia        confirmed   1.000000 -0.247581
               PM25       -0.247581  1.000000
Illinois       confirmed   1.000000  0.021141
               PM25        0.021141  1.000000
Michigan       confirmed   1.000000 -0.222374
               PM25       -0.222374  1.000000
New York       confirmed   1.000000 -0.018658
               PM25       -0.018658  1.000000
North Carolina confirmed   1.000000  0.070613
               PM25        0.070613  1.000000
Ohio           confirmed   1.000000  0.125422
               PM25        0.125422  1.000000
Pennsylvania   confirmed   1.000000  0.001317
               PM25        0.001317  1.000000
Texas          confirmed   1.000000 -0.144295
               PM25       -0.144295  1.000000

In [86]:
m6.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.133271
               ozone       0.133271  1.000000
Florida        confirmed   1.000000 -0.312034
               ozone      -0.312034  1.000000
Georgia        confirmed   1.000000  0.062029
               ozone       0.062029  1.000000
Illinois       confirmed   1.000000  0.008308
               ozone       0.008308  1.000000
Michigan       confirmed   1.000000 -0.329459
               ozone      -0.329459  1.000000
New York       confirmed   1.000000  0.572834
               ozone       0.572834  1.000000
North Carolina confirmed   1.000000  0.089003
               ozone       0.089003  1.000000
Ohio           confirmed   1.000000  0.011034
               ozone       0.011034  1.000000
Pennsylvania   confirmed   1.000000  0.037200
               ozone       0.037200  1.000000
Texas          confirmed   1.000000 -0.192310
               ozone      -0.192310  1.000000

In [87]:
m6.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.089794
               PM10       -0.089794  1.000000
Florida        confirmed   1.000000 -0.174945
               PM10       -0.174945  1.000000
Georgia        confirmed   1.000000  0.525236
               PM10        0.525236  1.000000
Illinois       confirmed   1.000000  0.074057
               PM10        0.074057  1.000000
Michigan       confirmed   1.000000 -0.182254
               PM10       -0.182254  1.000000
New York       confirmed   1.000000  0.108662
               PM10        0.108662  1.000000
North Carolina confirmed   1.000000 -0.161678
               PM10       -0.161678  1.000000
Ohio           confirmed   1.000000  0.054945
               PM10        0.054945  1.000000
Pennsylvania   confirmed   1.000000  0.044509
               PM10        0.044509  1.000000
Texas          confirmed   1.000000 -0.348991
               PM10       -0.348991  1.000000

## July

In [88]:
m7 = df[df['date'].dt.month == 7]

In [89]:
m7.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.345950
               PM25        0.345950  1.000000
Florida        confirmed   1.000000 -0.013470
               PM25       -0.013470  1.000000
Georgia        confirmed   1.000000 -0.323178
               PM25       -0.323178  1.000000
Illinois       confirmed   1.000000 -0.004894
               PM25       -0.004894  1.000000
Michigan       confirmed   1.000000  0.091043
               PM25        0.091043  1.000000
New York       confirmed   1.000000  0.430428
               PM25        0.430428  1.000000
North Carolina confirmed   1.000000  0.059091
               PM25        0.059091  1.000000
Ohio           confirmed   1.000000 -0.063960
               PM25       -0.063960  1.000000
Pennsylvania   confirmed   1.000000  0.032024
               PM25        0.032024  1.000000
Texas          confirmed   1.000000  0.243882
               PM25        0.243882  1.000000

In [90]:
m7.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000 -0.025198
               ozone      -0.025198  1.000000
Florida        confirmed   1.000000 -0.155581
               ozone      -0.155581  1.000000
Georgia        confirmed   1.000000  0.114518
               ozone       0.114518  1.000000
Illinois       confirmed   1.000000 -0.017544
               ozone      -0.017544  1.000000
Michigan       confirmed   1.000000  0.357319
               ozone       0.357319  1.000000
New York       confirmed   1.000000  0.472104
               ozone       0.472104  1.000000
North Carolina confirmed   1.000000  0.207484
               ozone       0.207484  1.000000
Ohio           confirmed   1.000000 -0.050705
               ozone      -0.050705  1.000000
Pennsylvania   confirmed   1.000000  0.127300
               ozone       0.127300  1.000000
Texas          confirmed   1.000000 -0.482563
               ozone      -0.482563  1.000000

In [91]:
m7.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.094954
               PM10       -0.094954  1.000000
Florida        confirmed   1.000000 -0.239217
               PM10       -0.239217  1.000000
Georgia        confirmed   1.000000 -0.261356
               PM10       -0.261356  1.000000
Illinois       confirmed   1.000000  0.040705
               PM10        0.040705  1.000000
Michigan       confirmed   1.000000  0.127923
               PM10        0.127923  1.000000
New York       confirmed   1.000000  0.482115
               PM10        0.482115  1.000000
North Carolina confirmed   1.000000 -0.008899
               PM10       -0.008899  1.000000
Ohio           confirmed   1.000000  0.057974
               PM10        0.057974  1.000000
Pennsylvania   confirmed   1.000000  0.068061
               PM10        0.068061  1.000000
Texas          confirmed   1.000000 -0.062438
               PM10       -0.062438  1.000000

## August

In [92]:
m8 = df[df['date'].dt.month == 8]

In [93]:
m8.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000 -0.303150
               PM25       -0.303150  1.000000
Florida        confirmed   1.000000 -0.016270
               PM25       -0.016270  1.000000
Georgia        confirmed   1.000000  0.062161
               PM25        0.062161  1.000000
Illinois       confirmed   1.000000 -0.167504
               PM25       -0.167504  1.000000
Michigan       confirmed   1.000000 -0.135059
               PM25       -0.135059  1.000000
New York       confirmed   1.000000 -0.068517
               PM25       -0.068517  1.000000
North Carolina confirmed   1.000000  0.169947
               PM25        0.169947  1.000000
Ohio           confirmed   1.000000  0.069610
               PM25        0.069610  1.000000
Pennsylvania   confirmed   1.000000 -0.003237
               PM25       -0.003237  1.000000
Texas          confirmed   1.000000  0.492079
               PM25        0.492079  1.000000

In [94]:
m8.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000 -0.139638
               ozone      -0.139638  1.000000
Florida        confirmed   1.000000 -0.238011
               ozone      -0.238011  1.000000
Georgia        confirmed   1.000000  0.415577
               ozone       0.415577  1.000000
Illinois       confirmed   1.000000  0.118335
               ozone       0.118335  1.000000
Michigan       confirmed   1.000000  0.227891
               ozone       0.227891  1.000000
New York       confirmed   1.000000  0.038749
               ozone       0.038749  1.000000
North Carolina confirmed   1.000000  0.196000
               ozone       0.196000  1.000000
Ohio           confirmed   1.000000 -0.041290
               ozone      -0.041290  1.000000
Pennsylvania   confirmed   1.000000  0.083920
               ozone       0.083920  1.000000
Texas          confirmed   1.000000 -0.115809
               ozone      -0.115809  1.000000

In [95]:
m8.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.345293
               PM10       -0.345293  1.000000
Florida        confirmed   1.000000 -0.121649
               PM10       -0.121649  1.000000
Georgia        confirmed   1.000000 -0.391341
               PM10       -0.391341  1.000000
Illinois       confirmed   1.000000  0.016870
               PM10        0.016870  1.000000
Michigan       confirmed   1.000000 -0.049837
               PM10       -0.049837  1.000000
New York       confirmed   1.000000  0.130680
               PM10        0.130680  1.000000
North Carolina confirmed   1.000000  0.021203
               PM10        0.021203  1.000000
Ohio           confirmed   1.000000  0.194718
               PM10        0.194718  1.000000
Pennsylvania   confirmed   1.000000  0.076647
               PM10        0.076647  1.000000
Texas          confirmed   1.000000  0.316756
               PM10        0.316756  1.000000

## September

In [96]:
m9 = df[df['date'].dt.month == 9]

In [97]:
m9.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000 -0.194771
               PM25       -0.194771  1.000000
Florida        confirmed   1.000000  0.041867
               PM25        0.041867  1.000000
Georgia        confirmed   1.000000 -0.020139
               PM25       -0.020139  1.000000
Illinois       confirmed   1.000000 -0.101430
               PM25       -0.101430  1.000000
Michigan       confirmed   1.000000 -0.205760
               PM25       -0.205760  1.000000
New York       confirmed   1.000000  0.165596
               PM25        0.165596  1.000000
North Carolina confirmed   1.000000  0.324146
               PM25        0.324146  1.000000
Ohio           confirmed   1.000000 -0.007781
               PM25       -0.007781  1.000000
Pennsylvania   confirmed   1.000000  0.019688
               PM25        0.019688  1.000000
Texas          confirmed   1.000000  0.057778
               PM25        0.057778  1.000000

In [98]:
m9.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000 -0.000020
               ozone      -0.000020  1.000000
Florida        confirmed   1.000000 -0.181765
               ozone      -0.181765  1.000000
Georgia        confirmed   1.000000 -0.067539
               ozone      -0.067539  1.000000
Illinois       confirmed   1.000000  0.009957
               ozone       0.009957  1.000000
Michigan       confirmed   1.000000 -0.156099
               ozone      -0.156099  1.000000
New York       confirmed   1.000000  0.027390
               ozone       0.027390  1.000000
North Carolina confirmed   1.000000  0.139294
               ozone       0.139294  1.000000
Ohio           confirmed   1.000000 -0.076776
               ozone      -0.076776  1.000000
Pennsylvania   confirmed   1.000000  0.003797
               ozone       0.003797  1.000000
Texas          confirmed   1.000000 -0.020162
               ozone      -0.020162  1.000000

In [99]:
m9.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.300459
               PM10       -0.300459  1.000000
Florida        confirmed   1.000000  0.061639
               PM10        0.061639  1.000000
Georgia        confirmed   1.000000 -0.205184
               PM10       -0.205184  1.000000
Illinois       confirmed   1.000000  0.035440
               PM10        0.035440  1.000000
Michigan       confirmed   1.000000 -0.191895
               PM10       -0.191895  1.000000
New York       confirmed   1.000000  0.173962
               PM10        0.173962  1.000000
North Carolina confirmed   1.000000  0.061715
               PM10        0.061715  1.000000
Ohio           confirmed   1.000000  0.148928
               PM10        0.148928  1.000000
Pennsylvania   confirmed   1.000000  0.142467
               PM10        0.142467  1.000000
Texas          confirmed   1.000000 -0.328893
               PM10       -0.328893  1.000000

## October

In [100]:
m10 = df[df['date'].dt.month == 10]

In [101]:
m10.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000 -0.120996
               PM25       -0.120996  1.000000
Florida        confirmed   1.000000 -0.278118
               PM25       -0.278118  1.000000
Georgia        confirmed   1.000000  0.174276
               PM25        0.174276  1.000000
Illinois       confirmed   1.000000 -0.007199
               PM25       -0.007199  1.000000
Michigan       confirmed   1.000000 -0.520061
               PM25       -0.520061  1.000000
New York       confirmed   1.000000 -0.081573
               PM25       -0.081573  1.000000
North Carolina confirmed   1.000000  0.254020
               PM25        0.254020  1.000000
Ohio           confirmed   1.000000 -0.010120
               PM25       -0.010120  1.000000
Pennsylvania   confirmed   1.000000  0.024738
               PM25        0.024738  1.000000

In [102]:
m10.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.041086
               ozone       0.041086  1.000000
Florida        confirmed   1.000000 -0.076497
               ozone      -0.076497  1.000000
Georgia        confirmed   1.000000  0.287157
               ozone       0.287157  1.000000
Illinois       confirmed   1.000000 -0.048877
               ozone      -0.048877  1.000000
Michigan       confirmed   1.000000 -0.236823
               ozone      -0.236823  1.000000
New York       confirmed   1.000000  0.415911
               ozone       0.415911  1.000000
North Carolina confirmed   1.000000  0.097802
               ozone       0.097802  1.000000
Ohio           confirmed   1.000000 -0.088776
               ozone      -0.088776  1.000000
Pennsylvania   confirmed   1.000000  0.086795
               ozone       0.086795  1.000000

In [103]:
m10.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.293462
               PM10       -0.293462  1.000000
Florida        confirmed   1.000000 -0.217115
               PM10       -0.217115  1.000000
Georgia        confirmed   1.000000  0.083589
               PM10        0.083589  1.000000
Illinois       confirmed   1.000000  0.020861
               PM10        0.020861  1.000000
Michigan       confirmed   1.000000 -0.271771
               PM10       -0.271771  1.000000
New York       confirmed   1.000000  0.225431
               PM10        0.225431  1.000000
North Carolina confirmed   1.000000  0.178473
               PM10        0.178473  1.000000
Ohio           confirmed   1.000000  0.160840
               PM10        0.160840  1.000000
Pennsylvania   confirmed   1.000000  0.061280
               PM10        0.061280  1.000000

## November

In [104]:
m11 = df[df['date'].dt.month == 11]

In [105]:
m11.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.066382
               PM25        0.066382  1.000000
Florida        confirmed   1.000000 -0.446789
               PM25       -0.446789  1.000000
Georgia        confirmed   1.000000  0.141784
               PM25        0.141784  1.000000
Illinois       confirmed   1.000000 -0.069854
               PM25       -0.069854  1.000000
Michigan       confirmed   1.000000 -0.421232
               PM25       -0.421232  1.000000
New York       confirmed   1.000000  0.103208
               PM25        0.103208  1.000000
North Carolina confirmed   1.000000  0.316203
               PM25        0.316203  1.000000
Ohio           confirmed   1.000000 -0.012716
               PM25       -0.012716  1.000000
Pennsylvania   confirmed   1.000000 -0.076166
               PM25       -0.076166  1.000000

In [106]:
m11.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.272195
               ozone       0.272195  1.000000
Florida        confirmed   1.000000  0.056743
               ozone       0.056743  1.000000
Georgia        confirmed   1.000000  0.067442
               ozone       0.067442  1.000000
Illinois       confirmed   1.000000 -0.077926
               ozone      -0.077926  1.000000
Michigan       confirmed   1.000000 -0.394871
               ozone      -0.394871  1.000000
New York       confirmed   1.000000 -0.785470
               ozone      -0.785470  1.000000
North Carolina confirmed   1.000000 -0.011567
               ozone      -0.011567  1.000000
Ohio           confirmed   1.000000 -0.283675
               ozone      -0.283675  1.000000
Pennsylvania   confirmed   1.000000 -0.205453
               ozone      -0.205453  1.000000

In [107]:
m11.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.081221
               PM10       -0.081221  1.000000
Florida        confirmed   1.000000 -0.403859
               PM10       -0.403859  1.000000
Georgia        confirmed   1.000000  0.221966
               PM10        0.221966  1.000000
Illinois       confirmed   1.000000 -0.029755
               PM10       -0.029755  1.000000
Michigan       confirmed   1.000000 -0.565509
               PM10       -0.565509  1.000000
New York       confirmed   1.000000  0.416080
               PM10        0.416080  1.000000
North Carolina confirmed   1.000000  0.264078
               PM10        0.264078  1.000000
Ohio           confirmed   1.000000  0.030495
               PM10        0.030495  1.000000
Pennsylvania   confirmed   1.000000 -0.024323
               PM10       -0.024323  1.000000

## December

In [108]:
m12 = df[df['date'].dt.month == 12]
m12

,date,state,county,PM25,ozone,PM10,confirmed,deaths
date,,,,,,,,
2021-12-01,2021-12-01,California,Butte,23.2,0.035,36,25476,318
2021-12-01,2021-12-01,California,Butte,23.2,0.029,36,25476,318
2021-12-01,2021-12-01,California,Butte,2.4,0.035,36,25476,318
2021-12-01,2021-12-01,California,Butte,2.4,0.029,36,25476,318
2021-12-01,2021-12-01,California,Butte,24.1,0.035,36,25476,318
...,...,...,...,...,...,...,...,...
2021-12-24,2021-12-24,Illinois,Madison,7.9,0.031,19,46476,715
2021-12-24,2021-12-24,Illinois,Madison,11.5,0.031,19,46476,715
2021-12-24,2021-12-24,Illinois,Madison,11.4,0.031,19,46476,715
2021-12-24,2021-12-24,Illinois,Madison,9.8,0.031,19,46476,715
2021-12-24,2021-12-24,Illinois,Madison,7.0,0.031,19,46476,715

In [109]:
m12.groupby('state')[['confirmed','PM25']].corr()

                          confirmed      PM25
state
California     confirmed   1.000000  0.130805
               PM25        0.130805  1.000000
Florida        confirmed   1.000000 -0.254303
               PM25       -0.254303  1.000000
Georgia        confirmed   1.000000 -0.459141
               PM25       -0.459141  1.000000
Illinois       confirmed   1.000000  0.119351
               PM25        0.119351  1.000000
Michigan       confirmed   1.000000  0.527532
               PM25        0.527532  1.000000
New York       confirmed   1.000000  0.698886
               PM25        0.698886  1.000000
North Carolina confirmed   1.000000 -0.163609
               PM25       -0.163609  1.000000
Ohio           confirmed   1.000000  0.198595
               PM25        0.198595  1.000000
Pennsylvania   confirmed   1.000000  0.086176
               PM25        0.086176  1.000000

In [110]:
m12.groupby('state')[['confirmed','ozone']].corr()

                          confirmed     ozone
state
California     confirmed   1.000000  0.018219
               ozone       0.018219  1.000000
Florida        confirmed   1.000000  0.129675
               ozone       0.129675  1.000000
Georgia        confirmed   1.000000 -0.125682
               ozone      -0.125682  1.000000
Illinois       confirmed   1.000000 -0.069981
               ozone      -0.069981  1.000000
Michigan       confirmed   1.000000 -0.708490
               ozone      -0.708490  1.000000
New York       confirmed   1.000000 -0.871267
               ozone      -0.871267  1.000000
North Carolina confirmed   1.000000 -0.260029
               ozone      -0.260029  1.000000
Ohio           confirmed   1.000000 -0.336382
               ozone      -0.336382  1.000000
Pennsylvania   confirmed   1.000000 -0.238978
               ozone      -0.238978  1.000000

In [111]:
m12.groupby('state')[['confirmed','PM10']].corr()

                          confirmed      PM10
state
California     confirmed   1.000000 -0.021749
               PM10       -0.021749  1.000000
Florida        confirmed   1.000000 -0.411796
               PM10       -0.411796  1.000000
Georgia        confirmed   1.000000 -0.420451
               PM10       -0.420451  1.000000
Illinois       confirmed   1.000000  0.067155
               PM10        0.067155  1.000000
Michigan       confirmed   1.000000 -0.199265
               PM10       -0.199265  1.000000
New York       confirmed   1.000000  0.723191
               PM10        0.723191  1.000000
North Carolina confirmed   1.000000 -0.351294
               PM10       -0.351294  1.000000
Ohio           confirmed   1.000000  0.155733
               PM10        0.155733  1.000000
Pennsylvania   confirmed   1.000000  0.048955
               PM10        0.048955  1.000000